ANALYSIS_PENDING = "ANALYSIS PENDING"

RUNNING_SIMULATIONS = "RUNNING SIMULATIONS"
FAILED_SIMULATIONS = "FAILED SIMULATIONS"

TRAINING_REGRESSOR = "TRAINING REGRESSOR"
FAILED_REGRESSOR = "FAILED REGRESSOR"

TRAINING_GENERATOR = "TRAINING GENERATOR"
FAILED_GENERATOR = "FAILED GENERATOR"

GENERATING_RESULTS = "GENERATING RESULTS"
FAILED_RESULTS = "FAILED RESULTS"

UPDATED = "UPDATED"