from IDFObject.IDFObject import IDFObject
    
class WaterToAirHeatPump(IDFObject):
    __IDFName__ = 'HVACTemplate:Zone:WaterToAirHeatPump'
    Properties = [
        'ZoneName',
        'TemplateThermostatName',
        'CoolingSupplyAirFlowRate',
        'HeatingSupplyAirFlowRate',
        'NoLoadSupplyAirFlowRate',
        'ZoneHeatingSizingFactor',
        'ZoneCoolingSizingFactor',
        'OutdoorAirMethod',
        'OutdoorAirFlowRateperPerson',
        'OutdoorAirFlowRateperZoneFloorArea',
        'OutdoorAirFlowRateperZone',
        'SystemAvailabilityScheduleName',
        'SupplyFanOperatingModeScheduleName',
        'SupplyFanPlacement',
        'SupplyFanTotalEfficiency',
        'SupplyFanDeltaPressure',
        'SupplyFanMotorEfficiency',
        'CoolingCoilType',
        'CoolingCoilGrossRatedTotalCapacity',
        'CoolingCoilGrossRatedSensibleHeatRatio',
        'CoolingCoilGrossRatedCOP',
        'HeatPumpHeatingCoilType',
        'HeatPumpHeatingCoilGrossRatedCapacity',
        'HeatPumpHeatingCoilGrossRatedCOP',
        'SupplementalHeatingCoilAvailabilityScheduleName',
        'SupplementalHeatingCoilCapacity',
        'MaximumCyclingRate',
        'HeatPumpTimeConstant',
        'FractionofOnCyclePowerUse',
        'HeatPumpFanDelayTime',
        'DedicatedOutdoorAirSystemName',
        'SupplementalHeatingCoilType',
        'ZoneCoolingDesignSupplyAirTemperatureInputMethod',
        'ZoneCoolingDesignSupplyAirTemperature',
        'ZoneCoolingDesignSupplyAirTemperatureDifference',
        'ZoneHeatingDesignSupplyAirTemperatureInputMethod',
        'ZoneHeatingDesignSupplyAirTemperature',
        'ZoneHeatingDesignSupplyAirTemperatureDifference',
        'HeatPumpCoilWaterFlowMode',
        'DesignSpecificationOutdoorAirObjectName',
        'DesignSpecificationZoneAirDistributionObjectName',
    ]

    def __init__(self, propertiesDict: dict()):
        super().__init__(self.Properties, propertiesDict)

WaterToAirHeatPump.Default = dict(
    CoolingSupplyAirFlowRate = 'autosize',
    HeatingSupplyAirFlowRate = 'autosize',
    NoLoadSupplyAirFlowRate = '',
    ZoneHeatingSizingFactor = 1.2,
    ZoneCoolingSizingFactor = 1.2,
    OutdoorAirMethod = '',
    OutdoorAirFlowRateperPerson = '',
    OutdoorAirFlowRateperZoneFloorArea = '',
    OutdoorAirFlowRateperZone = '',
    SystemAvailabilityScheduleName = '',
    SupplyFanOperatingModeScheduleName = '',
    SupplyFanPlacement = 'DrawThrough',
    SupplyFanTotalEfficiency = 0.7,
    SupplyFanDeltaPressure = 75,
    SupplyFanMotorEfficiency = 0.9,
    CoolingCoilType = 'Coil:Cooling:WaterToAirHeatPump:EquationFit',
    CoolingCoilGrossRatedTotalCapacity = 'autosize',
    CoolingCoilGrossRatedSensibleHeatRatio = 'autosize',
    CoolingCoilGrossRatedCOP = 3.2,
    HeatPumpHeatingCoilType = 'Coil:Heating:WaterToAirHeatPump:EquationFit',
    HeatPumpHeatingCoilGrossRatedCapacity = 'autosize',
    HeatPumpHeatingCoilGrossRatedCOP = 2.8,
    SupplementalHeatingCoilAvailabilityScheduleName = '',
    SupplementalHeatingCoilCapacity = 'autosize',
    MaximumCyclingRate = 2.5,
    HeatPumpTimeConstant = 60,
    FractionofOnCyclePowerUse = 0.01,
    HeatPumpFanDelayTime = 60,
    DedicatedOutdoorAirSystemName = '',
    SupplementalHeatingCoilType = 'Electric',
    ZoneCoolingDesignSupplyAirTemperatureInputMethod = 'SupplyAirTemperature',
    ZoneCoolingDesignSupplyAirTemperature = 12.5,
    ZoneCoolingDesignSupplyAirTemperatureDifference = '',
    ZoneHeatingDesignSupplyAirTemperatureInputMethod = 'SupplyAirTemperature',
    ZoneHeatingDesignSupplyAirTemperature = 50,
    ZoneHeatingDesignSupplyAirTemperatureDifference = '',
    HeatPumpCoilWaterFlowMode = '',
    DesignSpecificationOutdoorAirObjectName = '',
    DesignSpecificationZoneAirDistributionObjectName = '',
)